
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://cdn.paddle.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https: https://lkezjcqdvxfrrfwwyjcp.supabase.co; connect-src 'self' https://lkezjcqdvxfrrfwwyjcp.supabase.co https://api.stripe.com https://api.paddle.com https://www.google-analytics.com; frame-src 'self' https://js.stripe.com https://checkout.paddle.com;"

[[redirects]]
  from = "/api/*"
  to = "https://lkezjcqdvxfrrfwwyjcp.supabase.co/functions/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_ENV = "production"

[context.staging.environment]
  REACT_APP_ENV = "staging"
