
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkezjcqdvxfrrfwwyjcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZXpqY3FkdnhmcnJmd3d5amNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjM1NDMsImV4cCI6MjA2MzMzOTU0M30.EEx2NeZj6hNP25hEdJeEQaFpdALtPix4oxOUxjcj8p8";

// Create and export the Supabase client
// We're ignoring the Database type here since it's auto-generated and may not match our actual schema
// We'll use our own types from database.ts for type safety
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
